### ISSUE TITLE
Westfall broke

### ISSUE THREAD

**Issue by ew-git** [shawn571/Guidelime_CainesAllianceGuides#1]
The latest update broke Westfall Alliance 16-19.lua
this line
```
Talk to Silva Fil'naveth to fly to Rut'theran Village.[G44.14,45.23,1,Moonglade][A Druid]v cb
```
I think should be

```
Talk to Silva Fil'naveth to fly to Rut'theran Village.[G44.14,45.23,1Moonglade][A Druid]
```
(remove comma and `v cb` at the end)

**Comment by shawn571** [comment]
Thanks for the report. Fixed and updated - should be available for download soon
